# Generated by Django 3.2.9 on 2021-11-07 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_abbreviatedlink_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abbreviatedlink',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abbreviatedlink',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
