# Generated by Django 3.2.9 on 2021-11-08 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20211107_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abbreviatedlink',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='abbreviatedlink',
            unique_together={('owner', 'urlhash')},
        ),
    ]
