# Generated by Django 3.2.9 on 2021-11-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20211108_1315'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='abbreviatedlink',
            unique_together={('owner', 'parent_link')},
        ),
    ]
