# Generated by Django 3.2.9 on 2021-11-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_abbreviatedlink_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abbreviatedlink',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Счетчик'),
        ),
        migrations.AlterField(
            model_name='abbreviatedlink',
            name='created_time_and_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='abbreviatedlink',
            name='parent_link',
            field=models.URLField(max_length=300, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='abbreviatedlink',
            name='urlhash',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Персональный код'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP адресс пользователя'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='time_and_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время перехода'),
        ),
    ]
