# Generated by Django 4.0.1 on 2022-02-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_remove_user_is_confirmed_alter_abbreviatedlink_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_sms_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
