# Generated by Django 4.0.1 on 2022-02-20 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='transition',
            name='abbr_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.abbreviatedlink'),
        ),
    ]
